services:
  - type: web
    name: projeto-gestao-2-0
    env: python
    plan: free
    buildCommand: pip install -r requirements_producao.txt
    startCommand: gunicorn --config gunicorn.conf.py app_producao:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app_producao.py
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false 